peft v0.7.0 (#10)
* updated v0.7.0

* MNT: Re-rendered with conda-build 3.27.0, conda-smithy 3.30.1, and conda-forge-pinning 2023.12.05.22.51.14

* Set lower pin on transformers>=4.0.0 in test.requires

Try to fix `ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers'`, possibly due to the test build installing transformers=2.1.1. Also resorted runtime dependencies alphabetically

---------

Co-authored-by: Wei Ji <23487320+weiji14@users.noreply.github.com>