Set lower pin on transformers>=4.0.0 in test.requires
Try to fix `ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers'`, possibly due to the test build installing transformers=2.1.1. Also resorted runtime dependencies alphabetically